server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name sokolrock.org www.sokolrock.org;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 4443 ssl;
    listen [::]:4443 ssl;
    http2 on;
    server_name sokolrock.org www.sokolrock.org;

    ssl_certificate /etc/letsencrypt/live/sokolrock.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sokolrock.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
